### PR TITLE
Adding configuration for jaiabot-web deb package

### PR DESCRIPTION
**Pull request by ferrom-jaia**

### CODE REVIEW

**Review by jason-jaia — COMMENTED** [review]
@ferrom-jaia It depends on itself? Is that standard?

**Comment by ferrom-jaia** [comment]
> @ferrom-jaia It depends on itself? Is that standard?

I saw how the other packages were configured (looking at jaiabot-web in the same file) and added the jaiabot-plot package as a dependency to jaiabot-embedded

**Comment by jason-jaia** [comment]
haha - my mistake.  I didn't parse the context of the git diff.

**Comment by jason-jaia** [comment]
The dependencies aren't right though - jaiabot_plot doesn't need all of those things. And there's an issue with h5py that needs to be resolved. (see Slack)

**Review by jason-jaia — APPROVED** [review]

**Comment by jason-jaia** [comment]
updates to PR look good.

**Pull request merged**
